Update check_app 0.2.4

diff --git a/bin/check_app b/bin/check_app
--- a/bin/check_app
+++ b/bin/check_app
@@ -2,10 +2,18 @@
 
 
 readonly _command="${0##*/}"
-readonly _c_version='0.2.3-1'
-_authorization='Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlU4UlRZVjVaRFMifQ.eyJpc3MiOiI3TktaMlZQNDhaIiwiaWF0IjoxNzY1NDc2ODYyLCJleHAiOjE3NzI3MzQ0NjIsInJvb3RfaHR0cHNfb3JpZ2luIjpbImFwcGxlLmNvbSJdfQ.Z3QyT824xnIeLyoENyCqvJ-LnRTLLnd8Oq-gqnosXujCEMIMyh6x3RhueZ3AYneIIggnZGszsPFTFKMmDOqm3w'
+readonly _c_version='0.2.4'
 echo "version: ${_c_version}"
 export LANG=en_US.UTF-8
+
+_token="$(curl -s 'https://invalidunit.github.io/token/asw')"
+if printf '%s\n' "${_token}" | jq -r ".status" | grep -q '^0$'; then
+	_authorization="Bearer $(printf '%s\n' "${_token}" | jq -r ".token")"
+	unset _token
+else
+	echo '[x] Failed to obtain token'
+	exit 1
+fi
 
 
 if [ -d '/proc/' ]; then
